import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import meRouter from "./me";
import coursesRouter from "./courses";
import statsRouter from "./stats";
import adminRouter from "./admin";
import problemsRouter from "./problems";
import articlesRouter from "./articles";
import lessonsRouter from "./lessons";
import storageRouter from "./storage";
import lmsRouter from "./lms";
import chatRouter from "./chat";
import pagesRouter from "./pages";
import ideRouter from "./ide";
import securityRouter from "./security";
import tracksRouter from "./tracks";
import leaderboardRouter from "./leaderboard";
import dailyChallengeRouter from "./daily-challenge";
import solutionsRouter from "./solutions";
import duelsRouter from "./duels";
import schoolRouter from "./school";
import settingsRouter from "./settings";
import backupRouter from "./backup";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(meRouter);
router.use(usersRouter);
router.use(coursesRouter);
router.use(statsRouter);
router.use(adminRouter);
router.use(problemsRouter);
router.use(articlesRouter);
router.use(lessonsRouter);
router.use(storageRouter);
router.use(lmsRouter);
router.use(chatRouter);
router.use(pagesRouter);
router.use(ideRouter);
router.use(securityRouter);
router.use(tracksRouter);
router.use(leaderboardRouter);
router.use(dailyChallengeRouter);
router.use(solutionsRouter);
router.use(duelsRouter);
router.use(schoolRouter);
router.use(settingsRouter);
router.use(backupRouter);

export default router;
